version: 2.1
jobs:
  test:
    docker:
      - image: cypress/base:12.16.1
      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: postgrespassword
    steps:
      - checkout

workflows:
  hasura_workflow:
    jobs:
      - test
