# https://circleci.com/docs/2.0/postgres-config/
version: 2.1
jobs:
  test:
    docker:
      - image: cypress/base:12.16.1

      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: postgrespassword

      - image: hasura/graphql-engine:v1.1.1
        environment:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/postgres
          HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
          HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
          HASURA_GRAPHQL_NO_OF_RETRIES: 30

    steps:
      - checkout
      - run:
          name: install dependencies 📦
          command: npm ci
      - run:
          name: Wait for PG db
          command: npx wait-on --timeout 30000 tcp:5432 && echo 'Posgres is ready'
      - run:
          name: check migrations
          command: npx hasura migrate status
          working_directory: my-project
      - run:
          name: apply migrations
          command: npx hasura migrate apply
          working_directory: my-project
      - run:
          name: check applied migrations
          command: npx hasura migrate status
          working_directory: my-project

      - run:
          name: Execute Cypress tests 🧪
          command: npx cypress run

workflows:
  hasura_workflow:
    jobs:
      - test
